image: node:18.16-alpine3.18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run generate

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public && cp -rf ./public
  artifacts:
    paths:
      - public

cache:
  paths:
    - node_modules
    - dist
