image: node:18.16-alpine3.18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install

pages:
  stage: deploy
  script:
    - npm run generate
    - rm -rf public
    - mkdir public && cp -rf dist/* public
  artifacts:
    paths:
      - public

cache:
  paths:
    - node_modules

