image: node:18.16-alpine3.18

workflow:
  rules: 
    - if: $CI_DEFAULT_BRANCH == "main"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install

pages:
  stage: deploy
  script:
    - npm run generate
    - cp -rf .output/public/* public
  artifacts:
    paths:
      - public

cache:
  paths:
    - node_modules
    - dist
